### PR TITLE
Add objects from bank 6 and bank 13 + base bullet logic

### PR DESCRIPTION
**Pull request by up-left**
Thanks for accepting my pull requests! Here is a new one.

It adds some creatures and machines into the project.
screen1
screen2
screen3
screen4
screen5
screen6
screen7

Since I was developing shooting creatures too, my code contains some duplicated functionality with new SceneCPUParticle. I think it's better to merge two solutions before implementing new objects.

Since cannons from bank 13 spawn a lot of particles, I had different bugs and requirements for them.
1. MoveAndCollide is better than just Translate. Some particles can hit players behind corners if a particle has high speed.
2. Adding a lot of nodes simultaneously, playing animations, and freeing them causes application to crash. You can try to do it on your computer, maybe it's a machine-dependent bug. I chose to implement some caching system which makes particle invisible after colliding and reinitializes it when needed. It also speeds up the game.
3. Also some objects have "pick one" feature. If you place two or more cannons in the area, they spawn the same amount of bullets as only one cannon spawns. This leads to some central mechanism for spawning. Emitting bullets at 50 fps and choosing one object as emitter requires some central timer.
4. Manipulating a lot of particles in physics_process causes internal Godot errors, CallDeferred is much better.

I will explore your solution better and write suggestions how they can be merged. Please see BaseBullet and BulletLayer for more info on my solution.

This code may contain bugs because I was in a hurry. I will add a commit with bugfixes and cleanups later.

Also this pull request contains white screen of death, moves GesturesObject to banks/common, disables collision shapes in a deferred way and adds hologram signal for Juni (if a player suddenly appears in a danger area).

### CODE REVIEW

**Comment by youkaicountry** [comment]
Thank you so much for all the awesome work! 

Apologies for the duplicated particle code, I set out to solve some issues when making the leaf objects (built-in particles weren't quite doing what I needed), and it ended up becoming a general particle system that I realized I could apply to bullets, so I tried it out on the water monsters.

The creature 17:3 (creepy water monster) is not done yet. Its bullets seem to exert a constant force in the direction of Juni as they travel, but I have not coded that yet. I may do that tonight, and then I will hold off on modifications until we decide on a way to unify the systems.

I'll check out this PR in detail and merge it later on tonight!

**Comment by youkaicountry** [comment]
Hello! I have reviewed the code, and am excited about the additions! It's nice to see more and more objects being implemented.

There are a couple architectural issues I have identified:

- Bullets in Knytt Stories are rendered on the same layer as the emitting object, but it appears with here they will always render at the same place. This can be important if there are waterfalls or something in the foreground. Maybe each bullet emitting object needs its own bullet layer attached, rather than a per-area one?

- WSOD should be attached to GDKnyttGame, so there is only one instance and it always renders over everything.

- I encountered intermittent crashes on death. Not sure why, but it might be related to the WSOD changes. I have some ideas.

I am going to merge this, and I will take a look at refactoring the WSOD changes.

Thanks again for the great PR!

**Comment by up-left** [comment]
I think you could drag some features from my solution to yours. If you face crash or internal errors or performance issues, you could use queues in SceneCPUParticles. The same applies to using KinematicBody2D and CallDeferred.
I could implement central per-area timer which calls back registered objects, picking one of them if required. Currently it only for bullets, but it would be useful for water monsters, for example. I think it will take intervals, delays and repeat counts, then execute callbacks with an index parameter.
What do you think about this plan?

**Comment by youkaicountry** [comment]
Not a bad plan, but what is the idea of the central timer rather than each object managing their own timers? Is it to stagger emissions so they don't all happen in the same frame?

**Comment by up-left** [comment]
Yes, it is used quite often. If all these water monsters had its own timer, they could not choose which one will shoot:
editor1
editor2

**Comment by youkaicountry** [comment]
Ah, good catch. 
That all sounds very good then!

**Comment by up-left** [comment]
OK! Will implement central timer later.

**Pull request merged**
